$storm_script = <<SCRIPT
#!/bin/bash

apt-get update
apt-get install wget -y
apt-get install unzip -y
apt-get install python-dev -y
apt-get install python-lxml -y
apt-get install python-pip -y
apt-get install git -y
apt-get install htop -y

# Install Java 8
echo "Installing Oracle Java 1.8 ...."
apt-get install python-software-properties -y
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
add-apt-repository ppa:webupd8team/java -y
apt-get update -y
apt-get install oracle-java8-installer -y
apt-get install ant -y

apt-get -f install

#Install Storm
cd /home/vagrant
wget http://www.us.apache.org/dist/storm/apache-storm-0.9.6/apache-storm-0.9.6.tar.gz
tar zxf apache-storm-0.9.6.tar.gz
ln -sf apache-storm-0.9.6 storm


#Fix owner
chown -R vagrant.vagrant storm apache*

cat > /etc/hosts <<EOF
127.0.0.1  vm-storm  vm-storm
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

#Configuration file setup
echo "Configuring storm"
mv /home/vagrant/apache/conf/storm.yaml /home/vagrant/apache/conf/storm.backup
cp /vagrant/supervisor.yaml /home/vagrant/storm/conf/storm.yaml

#Copy metric consumer
cp /vagrant/storm-metrics.jar /home/vagrant/storm/lib/storm-metrics.jar

#Copy example
cp /vagrant/storm-example.jar /home/vagrant

#install zookeeper
echo "Installing zookeeper"
apt-get -q -y --force-yes install zookeeper
apt-get install zookeeperd -y

echo "Starting zookeeper"
#service zookeeper start

sudo cp /vagrant/storm.sh /etc/profile.d/storm.sh
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :master do |master|
    master.vm.provider :virtualbox do |v|
      v.name = "vm-storm"
      v.customize ["modifyvm", :id, "--memory", "4096"]
    end
    master.vm.network :private_network, ip: "10.211.55.100"
    master.vm.hostname = "vm-storm"
    master.vm.network :forwarded_port, host:8080, guest: 8080
    master.vm.provision :shell, :inline => $storm_script
  end
end