$storm_script = <<SCRIPT
#!/bin/bash

apt-get update
apt-get install wget -y
apt-get install unzip -y
apt-get install python-dev -y
apt-get install python-lxml -y
apt-get install python-pip -y
apt-get install git -y
apt-get install htop -y

# Install Java 8
echo "Installing Oracle Java 1.8 ...."
apt-get install python-software-properties -y
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
add-apt-repository ppa:webupd8team/java -y
apt-get update -y
apt-get install oracle-java8-installer -y
apt-get install ant -y

apt-get -f install

#Install Storm
cd /home/vagrant
wget http://www.us.apache.org/dist/storm/apache-storm-0.9.6/apache-storm-0.9.6.tar.gz
tar zxf apache-storm-0.9.6.tar.gz
ln -sf apache-storm-0.9.6 storm

#Fix owner
chown -R vagrant.vagrant storm apache*

cat > /etc/hosts <<EOF
127.0.0.1  storm-nimbus  storm-nimbus
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

#Configuration file setup
echo "Configuring storm"

cd /home/vagrant
mv storm/conf/storm.yaml storm/conf/storm.backup

git clone https://github.com/doandongnguyen/storm-logstash.git
cp storm-logstash/target/storm-metrics-0.0.1-SNAPSHOT-jar-with-dependencies.jar storm/lib/
cp storm-logstash/vagrant/supervisor.yaml storm/conf/storm.yaml

#install zookeeper
echo "Installing zookeeper"
apt-get -q -y --force-yes install zookeeper
apt-get install zookeeperd -y

SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :master do |master|
    master.vm.provider :virtualbox do |v|
      v.name = "storm-nimbus"
      v.customize ["modifyvm", :id, "--memory", "4096"]
    end
    master.vm.network :private_network, ip: "10.211.56.100"
    master.vm.hostname = "storm-nimbus"
    master.vm.network :forwarded_port, host:8080, guest: 8080
    master.vm.provision :shell, :inline => $storm_script
  end
end